<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Title>Use Items Anywhere</Title>
    <Product>Use Items Anywhere</Product>
    <Copyright>Copyright © 2026 CJ-SPT</Copyright>
    <PackageLicenseExpression>CC-BY-NC-ND-4.0</PackageLicenseExpression>
    <Version>2.1.6</Version>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <!-- Gets the commit hash from git -->
  <Target Name="SetSourceRevisionId" BeforeTargets="InitializeSourceControlInformation">
    <Exec
      Command="git describe --long --always --dirty --exclude=* --abbrev=8"
      ConsoleToMSBuild="True"
      IgnoreExitCode="False"
    >
      <Output PropertyName="SourceRevisionId" TaskParameter="ConsoleOutput" />
    </Exec>
  </Target>
</Project>
